<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Help for Provider</title>
<link rel="stylesheet" type="text/css" href="css/styles.css"/></head>

<body>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0"  id="">
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" class="faqsubheading"><b>What is the E-Health Service? </b><a name="loggingintotx" id="loggingintotx"></a></td>   
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>E-Health Service is an innovative way to "repackage" your expertise, guidance, and time and charge your patients for online care. It gives you the ability to make money from patients or clients looking to work with you online. Tired of answering patient emails without getting paid? Now you can with E-Health Service. Want to charge your patients for personalized content and health literacy? Now you can with E-Health Service. As an extension of your clinic or facility, the E-Health Service allows you to provide your expertise online and get paid for it.</p></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top"   class="faqsubheading"><b>How does it work?</b><a name="changepassword" id="changepassword"></a></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;">
      <p>Once you turn-on the E-Health Service, you will create a service name, provide description of the service, list key features, and establish a monthly recurring price. When your patients 1st login, they will read your description of the service and if they want to receive the services you're are providing in their patient portal, they will enter their credit card information and subscribe to your service.</p> </td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td   class="faqsubheading"><b>What happens if I don't turn on the E-Health Service?</b><a name="createnewpatient" id="createnewpatient"></a></td>
    
  </tr>
   
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>If you don't turn on the E-Health Service, the system will not ask your patients to subscribe when they first login. You can still support them online via their patient portal with any communication, expertise, guidance, and content you want. </p>
	</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td class="faqsubheading" ><b>What happens if the E-Health Service is turned on, but a patient does not subscribe?</b><a name="modifypatient" id="modifypatient"></a></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
     <td valign="top" style="padding-left:50px;"><p>If you choose to turn on the E-Health Service , but a patient does not subscribe, they will not be able to login to their patient portal and receive online care from you.</p></td>
    
  </tr>
   <tr>
    <td colspan="2">&nbsp;</td>
    <td class="faqsubheading" ><b>How do the subscriptions work?</b><a name="resendpatient" id="resendpatient"></a></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
     <td valign="top" style="padding-left:50px;"><p>Once a month the system will automatically charge their credit card the amount you set for your E-Health Service. Your patients can stop their subscription at any time right from their patient portal. There are no contracts.<p></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading"><b>How much does it cost?</b><a name="createnewtreatment" id="createnewtreatment"></a></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p> There is no upfront cost to use the E-Health Service. We only earn a commission of 15% when you make money with the E-Health Service. At the end of every month, you will receive a check for 50% of the total revenue generated by your E-Health Service. All credit card processing, billing, reporting, remuneration to you, and support is included. <p></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading"  ><b>What reporting is provided?</b><a name="createnewtemplate" id="createnewtemplate"></a></td>
    
  </tr>
   <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>At anytime you can see a list of your current patients that are subscribing to your E-Health Service. You can also run a report at any time of your E-Health Service patients. To learn more, login and click on Feature Help.</p></td>
  </tr>

  <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading"  ><b>How much should I charge?</b><a name="createnewtemplate" id="createnewtemplate"></a></td>
    
  </tr>
   
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>It's up to you. There are many different ways to market the value of online care to your patients or clients and as such, there are many different ways to charge for your time and access to your content and expertise. In part, what you should charge depends on how much time you will be spending supporting them online and your business objectives. For a free consultation on how to 'repackage" your services and charge for them online, please email <a href="mailto:support@wholemedx.com"> support@wholemedx.com</a>. </p></td>
  </tr>
 <tr>
    <td colspan="3">&nbsp;</td>
  </tr>
 <tr>
 <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading"><b>Will I be able to have more than one service or charge one-time fees?</b><a name="createnewtemplate" id="createnewtemplate"></a></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>We plan on giving you the ability to create multiple service levels (e.g. bronze, silver, gold) and charge one-time fees (e.g. a single teleconsultation) in the future. </p></td>
  </tr>
 <tr>
    <td colspan="3">&nbsp;</td>
  </tr>
</table>
</body>
</html>
