<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Tx Xchange: Help for Provider</title>
<link rel="stylesheet" type="text/css" href="css/styles.css"/></head>

<body>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0"  id="">
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" class="faqsubheading">What is Tx Xchange's referral marketing service?<a name="loggingintotx" id="loggingintotx"></a></td>   
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>With TX's referral marketing service your patients or clients can much more effectively refer a friend, family member, or co-worker to your clinic, studio, of fitness facility and increase new customer volume for your business. While word-of-mouth referrals from existing patients or clients are likely an important source of new customers, most of them never end up on your schedule. Why? Because information about your business is usually forgotten, misplaced, or never looked up. Tx Xchange's referral marketing service solves this problem by making sure all the information necessary to schedule an appointment with your business is emailed to the person being referred. Your business' key information won't be easily forgotten or misplaced any longer. The service leverages the idea that the most effective form of marketing is recommendation-based where both parties know each other. Think of TX's referral marketing service as a significantly better "mousetrap" for word-of-mouth referrals.</p></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top"   class="faqsubheading">How does it work?<a name="changepassword" id="changepassword"></a></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;">
      <p>If you enable the service, your patients or clients will see a well-designed "call-to-action" button on their homepage (see screen shot below). Every time they login, they'll see the "call-to-action" asking them to refer people they know to your practice or business. When they click on it, a special window opens (see screen shot below) and the patient fills in some basic information about the person they want to refer and writes a personal note. They click "Send" and the personal note along with your business' telephone number, email address, website, mapped address, business overview, and logo are automatically emailed to your potential new patient or client.</p> </td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td   class="faqsubheading">How much does the referral marketing service cost?<a name="createnewpatient" id="createnewpatient"></a></td>
    
  </tr>
   
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>The service costs just $1.99 each time one of your patients or clients clicks "Send" to email a personal note and your business' key information to someone they know and want to refer. If the service is enabled, but your patients do not use it to refer your business or clinic, there is no cost. </p>
	<p>Once the service is enabled, there is nothing you or your staff needs to do other than use Tx Xchange with all of your patients and clients and help them achieve the outcomes they want. They'll do the rest.</p>
	</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td class="faqsubheading" >How cost-effective is the service?<a name="modifypatient" id="modifypatient"></a></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
     <td valign="top" style="padding-left:50px;"><p>Extremely. Let's take an example where 5 referrals are sent by your patients to a friend, family member, or co-worker and these referrals lead to 1 new customer for your business. The commission cost would be just $9.95 and the new revenue generated by that new patient or client could be $100s or even $1,000s of dollars depending on what you charge for your services, the number of appointments, and how long they stay a customer. </p></td>
    
  </tr>
   <tr>
    <td colspan="2">&nbsp;</td>
    <td class="faqsubheading" >Can I control how much my business spends on the marketing service?<a name="resendpatient" id="resendpatient"></a></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
     <td valign="top" style="padding-left:50px;"><p>Yes, limits can be set at the account level and patient level. For example: If you set a limit of 20 referrals for your business and no more than 3 from any one patient, the most you would pay in service commissions that month would be $39.80. Of this, only $5.97 would be from by any one patient. Any changes to the monthly limits will be made starting with the next billing cycle. The service will be billed for along with your monthly invoice.<p></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading">Are they contracts or minimum commitments? <a name="createnewtreatment" id="createnewtreatment"></a></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>There are no contracts; TX's marketing service is performance-based. On a monthly basis, the service levels can be adjusted, turned on, or turned off. <p></td>
    
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading"  >Is reporting provided to analyze results? <a name="createnewtemplate" id="createnewtemplate"></a></td>
    
  </tr>
   <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>Yes. TX's referral marketing service is built on the concept of closed-loop marketing which gives businesses the ability to determine which channels are the most efficient sources of new customers. With TX reporting you can see monthly totals, individual contact information for the person being referred, and the referring patient. You can easily compare the TX service data with any new patient report run from your existing billing or scheduling system. You'll be able to definitively see how effective the TX referral service is as a form of marketing and better allocate your marketing resources to the most efficient sources of new customers.</p></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading"  >How do I sign-up for the service?<a name="createnewtemplate" id="createnewtemplate"></a></td>
    
  </tr>
  
  <tr>
    <td colspan="2">&nbsp;</td>
    <td valign="top" style="padding-left:50px;"><p>As a TX Account Administrator, you simply click the Marketing Referral Service checkbox under the Premium Services tab and enter the monthly limits you want. Then, click on the Marketing tab and select Clinic Details. Make sure your business' address, contact information and company overview are up to date. It's that easy. For the 1st month you use the service, we suggest you set a limit of 15 referrals and no more than 3 for any one patient. This will give you a sufficient data set to assess value and optimize your use of the service in the future.</p><p>If you have any questions, please email: <a href="mailto:support@txxchange.com"> support@txxchange.com</a>. </p></td>
  </tr>
  <tr>
    <td colspan="3">&nbsp;</td>
  </tr>
 <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading">Patient Homepage with Referral Marketing Service Turned-On<a name="createnewtemplate" id="createnewtemplate"></a></td>
    
  </tr>
   <tr>
    <td colspan="3">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td>
		   <img src="images/refer-family-action.jpg" alt="" title="" border="0" />
	</td>
  </tr>

  <tr>
    <td colspan="3" height="25px">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td  class="faqsubheading">Patient Enters Basic Information to Make a Referral<a name="createnewtemplate" id="createnewtemplate"></a></td>
    
  </tr>
   <tr>
    <td colspan="3">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    <td >
		   <img src="images/refer-family-action-popup.jpg" alt="" title="" border="0" />		   
	</td>
  </tr>
</table>
</body>
</html>
